version: "3.7"

services:
  postgres:
    container_name: "postgres-db"
    image: tellesbruno/poadb:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=poatransport
      - TZ=America/Sao_Paulo
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=my.email@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=mysecret
      - TZ=America/Sao_Paulo
    ports:
      - "5050:80"
      - "5051:443"
    # volumes:
    #   - pg-admin-data:/srv/PGAdmin4
    #   - pga4volume:/var/lib/pgadmin

    networks:
      - default  

volumes:
  pg-admin-data:
  pga4volume:
  postgres-data:


networks:
  default:
    driver: bridge
